version: 0.0
os: linux
files:
  - source:  ./
    destination: /home/ubuntu/

hooks:
  ApplicationStop:
    - location: ./scripts/stop_minifi.sh
    timeout: 120
    runas: root

  BeforeInstall:
    - location: ./scripts/stop_minifi.sh
    timeout: 120
    runas: root
    
  AfterInstall:
    - location: ./scripts/install_dependencies.sh
    timeout: 120
    runas: root
