version: 0.0
os: linux
files:
  - source:  ./
    destination: /home/ubuntu/

hooks:
  ApplicationStop:  
    - location: ./scripts/install_dependencies.sh
      timeout: 180  
      runas: root
  BeforeInstall:  
    - location: ./scripts/install_dependencies.sh
      timeout: 180  
      runas: root
  Install:
    - location: ./scripts/install_minifi.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: ./scripts/install_java.sh
      timeout: 180
      runas: root
