MiNiFi Config Version: 3
Flow Controller:
  name: from-minif24
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: a817ad5e-3b57-3b23-0000-000000000000
  name: GetFile
  class: org.apache.nifi.processors.standard.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Batch Size: '1'
    File Filter: '[^\.].*'
    Ignore Hidden Files: 'true'
    Input Directory: /home/ubuntu/minifi/operator-profile-input-data
    Keep Source File: 'true'
    Maximum File Age:
    Maximum File Size:
    Minimum File Age: 0 sec
    Minimum File Size: 0 B
    Path Filter:
    Polling Interval: 0 sec
    Recurse Subdirectories: 'false'
- id: a4a0ce63-e634-3d44-0000-000000000000
  name: MyProcessor
  class: com.jarvis.processors.edge.MyProcessor
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - MY_RELATIONSHIP_1
  Properties: {}
- id: 36edb56c-214d-3ea4-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_source_flowfile_start: ${lineageStartDate}
    m_source_now: ${now():toNumber()}
    origFileSize: ${fileSize}
    outfile.schema.name: out-flowfile
    schema.name: hello-world
- id: a102dfe7-9923-3995-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_query_filesize: ${fileSize}
    m_query_flowfile_start: ${lineageStartDate}
    m_query_now: ${now():toNumber()}
  annotation data: |-
    <criteria>
        <flowFilePolicy>USE_ORIGINAL</flowFilePolicy>
    </criteria>
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 88facb8b-02ba-329e-0000-000000000000
  name: GetFile/success/UpdateAttribute
  source id: a817ad5e-3b57-3b23-0000-000000000000
  source relationship names:
  - success
  destination id: 36edb56c-214d-3ea4-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 14eda6a6-cbf4-3eb0-0000-000000000000
  name: MyProcessor/MY_RELATIONSHIP/UpdateAttribute
  source id: a4a0ce63-e634-3d44-0000-000000000000
  source relationship names:
  - MY_RELATIONSHIP
  destination id: a102dfe7-9923-3995-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 00a18e01-9b1d-3c8e-0000-000000000000
  name: UpdateAttribute/success/100b119b-1428-1a16-4db1-919d0eab3f59
  source id: a102dfe7-9923-3995-0000-000000000000
  source relationship names:
  - success
  destination id: 100b119b-1428-1a16-4db1-919d0eab3f59
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 3929196c-8571-349e-0000-000000000000
  name: UpdateAttribute/success/MyProcessor
  source id: 36edb56c-214d-3ea4-0000-000000000000
  source relationship names:
  - success
  destination id: a4a0ce63-e634-3d44-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: 484f76dd-ea94-3980-0000-000000000000
  name: ''
  url: http://172.31.29.24:8080/nifi
  comment: ''
  timeout: 30 sec
  yield period: 0 sec
  transport protocol: RAW
  proxy host: ''
  proxy port: ''
  proxy user: ''
  proxy password: ''
  local network interface: ''
  Input Ports:
  - id: 100b1195-1428-1a16-fecc-6e423b27b91d
    name: From MiNiFi31
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1191-1428-1a16-ff47-251587ba3ca3
    name: From MiNiFi30
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 11761007-1a16-1428-0310-9361808295d0
    name: From MiNiFi11
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 11761005-1a16-1428-0840-bd9489847f79
    name: From MiNiFi10
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 1a161428-100b-1176-cc50-a54b7f888cad
    name: From MiNiFi17
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b117a-1428-1a16-981c-af3b47a874d6
    name: From MiNiFi16
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1181-1428-1a16-1ed1-7a580d0c180b
    name: From MiNiFi19
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b117f-1428-1a16-1113-06033bd30ccd
    name: From MiNiFi18
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 1176100f-1a16-1428-9d85-0d6c4cee28e7
    name: From MiNiFi13
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 1176100d-1a16-1428-d31e-1c04cf036324
    name: From MiNiFi12
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 1176100b-1a16-1428-4e5d-67c6ee86bc4b
    name: From MiNiFi15
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 11761009-1a16-1428-4f4e-140754f75618
    name: From MiNiFi14
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: a9ba4c36-0170-1000-eafb-0f89b0d68514
    name: From MiNiFi
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 01741000-6a16-1428-386c-6f780bba82be
    name: From MiNiFi3
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 01741003-6a16-1428-b06d-2d68ca2eb5f1
    name: From MiNiFi4
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 29d12bf9-0174-1000-8db7-f3962403ce9e
    name: From MiNiFi1
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 44286a16-0174-1000-ed54-9298400d6eb9
    name: From MiNiFi2
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 10031176-1428-1a16-3864-db1e342f521c
    name: From MiNiFi7
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 14281a16-1176-1003-550f-f63705f6808a
    name: From MiNiFi8
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 6a161428-1003-1174-e15e-7746083c26ca
    name: From MiNiFi5
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 10031174-1428-1a16-15a5-1d81069cf609
    name: From MiNiFi6
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1183-1428-1a16-c86d-797a011a8385
    name: From MiNiFi20
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 11761003-1a16-1428-a207-dcda263361d7
    name: From MiNiFi9
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1193-1428-1a16-1bbc-be5188029fb6
    name: From MiNiFi22
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b118f-1428-1a16-aaa5-e150e9917042
    name: From MiNiFi21
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b118b-1428-1a16-4bbe-b27ded4f3b0c
    name: From MiNiFi28
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1189-1428-1a16-92a6-9142d5008712
    name: From MiNiFi27
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b118d-1428-1a16-b681-1f105aaff344
    name: From MiNiFi29
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b119b-1428-1a16-4db1-919d0eab3f59
    name: From MiNiFi24
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1197-1428-1a16-73d4-c5551995e2a8
    name: From MiNiFi23
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1187-1428-1a16-5a98-b973d31feeb0
    name: From MiNiFi26
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 100b1185-1428-1a16-7e77-671bd7f84ce2
    name: From MiNiFi25
    comment: ''
    max concurrent tasks: 2
    use compression: false
  Output Ports: []
NiFi Properties Overrides: {}
