MiNiFi Config Version: 3
Flow Controller:
  name: from-minif3
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: a817ad5e-3b57-3b23-0000-000000000000
  name: GetFile
  class: org.apache.nifi.processors.standard.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Batch Size: '1'
    File Filter: '[^\.].*'
    Ignore Hidden Files: 'true'
    Input Directory: /home/ubuntu/minifi/operator-profile-input-data
    Keep Source File: 'true'
    Maximum File Age:
    Maximum File Size:
    Minimum File Age: 0 sec
    Minimum File Size: 0 B
    Path Filter:
    Polling Interval: 0 sec
    Recurse Subdirectories: 'false'
- id: a4a0ce63-e634-3d44-0000-000000000000
  name: MyProcessor
  class: com.jarvis.processors.edge.MyProcessor
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - MY_RELATIONSHIP_1
  Properties: {}
- id: 36edb56c-214d-3ea4-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_source_flowfile_start: ${lineageStartDate}
    m_source_now: ${now():toNumber()}
    origFileSize: ${fileSize}
    outfile.schema.name: out-flowfile
    schema.name: hello-world
- id: a102dfe7-9923-3995-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_query_filesize: ${fileSize}
    m_query_flowfile_start: ${lineageStartDate}
    m_query_now: ${now():toNumber()}
  annotation data: |-
    <criteria>
        <flowFilePolicy>USE_ORIGINAL</flowFilePolicy>
    </criteria>
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 88facb8b-02ba-329e-0000-000000000000
  name: GetFile/success/UpdateAttribute
  source id: a817ad5e-3b57-3b23-0000-000000000000
  source relationship names:
  - success
  destination id: 36edb56c-214d-3ea4-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 14eda6a6-cbf4-3eb0-0000-000000000000
  name: MyProcessor/MY_RELATIONSHIP/UpdateAttribute
  source id: a4a0ce63-e634-3d44-0000-000000000000
  source relationship names:
  - MY_RELATIONSHIP
  destination id: a102dfe7-9923-3995-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 00a18e01-9b1d-3c8e-0000-000000000000
  name: UpdateAttribute/success/01741000-6a16-1428-386c-6f780bba82be
  source id: a102dfe7-9923-3995-0000-000000000000
  source relationship names:
  - success
  destination id: 01741000-6a16-1428-386c-6f780bba82be
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 3929196c-8571-349e-0000-000000000000
  name: UpdateAttribute/success/MyProcessor
  source id: 36edb56c-214d-3ea4-0000-000000000000
  source relationship names:
  - success
  destination id: a4a0ce63-e634-3d44-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: 484f76dd-ea94-3980-0000-000000000000
  name: ''
  url: http://172.31.29.24:8080/nifi
  comment: ''
  timeout: 30 sec
  yield period: 0 sec
  transport protocol: RAW
  proxy host: ''
  proxy port: ''
  proxy user: ''
  proxy password: ''
  local network interface: ''
  Input Ports:
  - id: a9ba4c36-0170-1000-eafb-0f89b0d68514
    name: From MiNiFi
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 01741000-6a16-1428-386c-6f780bba82be
    name: From MiNiFi3
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 01741003-6a16-1428-b06d-2d68ca2eb5f1
    name: From MiNiFi4
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 29d12bf9-0174-1000-8db7-f3962403ce9e
    name: From MiNiFi1
    comment: ''
    max concurrent tasks: 2
    use compression: false
  - id: 44286a16-0174-1000-ed54-9298400d6eb9
    name: From MiNiFi2
    comment: ''
    max concurrent tasks: 2
    use compression: false
  Output Ports: []
NiFi Properties Overrides: {}
