MiNiFi Config Version: 3
Flow Controller:
  name: mini-distr
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: a817ad5e-3b57-3b23-0000-000000000000
  name: GetFile
  class: org.apache.nifi.processors.standard.GetFile
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 1 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Batch Size: '1'
    File Filter: '[^\.].*'
    Ignore Hidden Files: 'true'
    Input Directory: /home/ubuntu/minifi/operator-profile-input-data
    Keep Source File: 'true'
    Maximum File Age:
    Maximum File Size:
    Minimum File Age: 0 sec
    Minimum File Size: 0 B
    Path Filter:
    Polling Interval: 0 sec
    Recurse Subdirectories: 'false'
- id: 2ba94ffe-8b51-3639-0000-000000000000
  name: LogAttribute
  class: org.apache.nifi.processors.standard.LogAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list:
  - success
  Properties:
    Attributes to Ignore:
    Attributes to Log:
    Log Level: info
    Log Payload: 'false'
    Log prefix:
    attributes-to-ignore-regex:
    attributes-to-log-regex: .*
    character-set: UTF-8
- id: def6aaa6-9038-3bde-0000-000000000000
  name: MyProcessor
  class: com.jarvis.processors.edge.MyProcessor
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    MY_PROPERTY: e
- id: 36edb56c-214d-3ea4-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_source_flowfile_start: ${lineageStartDate}
    m_source_now: ${now():toNumber()}
    origFileSize: ${fileSize}
    outfile.schema.name: out-flowfile
    schema.name: hello-world
- id: a102dfe7-9923-3995-0000-000000000000
  name: UpdateAttribute
  class: org.apache.nifi.processors.attributes.UpdateAttribute
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 0 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Delete Attributes Expression:
    Stateful Variables Initial Value:
    Store State: Do not store state
    m_query_filesize: ${fileSize}
    m_query_flowfile_start: ${lineageStartDate}
    m_query_now: ${now():toNumber()}
  annotation data: |-
    <criteria>
        <flowFilePolicy>USE_ORIGINAL</flowFilePolicy>
    </criteria>
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 88facb8b-02ba-329e-0000-000000000000
  name: GetFile/success/UpdateAttribute
  source id: a817ad5e-3b57-3b23-0000-000000000000
  source relationship names:
  - success
  destination id: 36edb56c-214d-3ea4-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 607830a5-d8d8-342f-0000-000000000000
  name: MyProcessor/MY_RELATIONSHIP/UpdateAttribute
  source id: def6aaa6-9038-3bde-0000-000000000000
  source relationship names:
  - MY_RELATIONSHIP
  destination id: a102dfe7-9923-3995-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 2e8dc0c7-8561-3f84-0000-000000000000
  name: MyProcessor/MY_RELATIONSHIP_1/LogAttribute
  source id: def6aaa6-9038-3bde-0000-000000000000
  source relationship names:
  - MY_RELATIONSHIP_1
  destination id: 2ba94ffe-8b51-3639-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 3716db1f-78a1-30c1-0000-000000000000
  name: UpdateAttribute/success/LogAttribute
  source id: a102dfe7-9923-3995-0000-000000000000
  source relationship names:
  - success
  destination id: 2ba94ffe-8b51-3639-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
- id: 968d6370-c7c4-303a-0000-000000000000
  name: UpdateAttribute/success/MyProcessor
  source id: 36edb56c-214d-3ea4-0000-000000000000
  source relationship names:
  - success
  destination id: def6aaa6-9038-3bde-0000-000000000000
  max work queue size: 100000
  max work queue data size: 5 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups: []
NiFi Properties Overrides: {}
